version: '3.8'

services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - kubenews_net
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data

  kubenews:
    image: raco21/kube-news-docker:${KUBE_NEWS_TAG}
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8080
    environment:
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgre
    networks:
      - kubenews_net

networks:
  kubenews_net:
    driver: bridge

volumes:
  postgre_docker_vol: